export const dataVocabulary = [
    
        {
            id: 1,
            word: "Annual",
            synonyms: "Yearly, once a year, every year",
            antonyms: "",
            meanings: "Hàng năm, mỗi năm 1 lần",
        },
        {
            id: 2,
            word: "Get on",
            synonyms: "Board",
            antonyms: "Get off",
            meanings: "Lên#xuống(tàu, xe, máy bay,...)",
        },
        {
            id: 3,
            word: "Ride a/the bus",
            synonyms: "Take a/the bus",
            antonyms: "",
            meanings: "Đi bằng xe buýt",
        },
        {
            id: 4,
            word: "Give +S.O a lift/ a ride",
            synonyms: "",
            antonyms: "Get + S.O a lift/ a ride",
            meanings: "Cho quá giang # đi quá giang",
        },
        {
            id: 5,
            word: "Relocate",
            synonyms: "Move to, Transfer(v): chuyến đi, chuyến công tác",
            antonyms: "",
            meanings: "Chuyển đến, dời đến",
        },
        {
            id: 6,
            word: "Merger",
            synonyms: "Combination",
            antonyms: "",
            meanings: "Sự xác nhập",
        },
        {
            id: 7,
            word: "Complimentary",
            synonyms: "Free",
            antonyms: "",
            meanings: "Miễn phí, cho tặng",
        },
        {
            id: 8,
            word: "Itinerary",
            synonyms: "Travel details, detailed schedule",
            antonyms: "",
            meanings: "Lịch chi tiết của một chuyến đi",
        },
        {
            id: 9,
            word: "Previous",
            synonyms: "Ago, last",
            antonyms: "Upcoming",
            meanings: "Trước đó # sắp diễn ra",
        },
        {
            id: 10,
            word: "Recruit",
            synonyms: "Hire, employ, seek, look for, search for",
            antonyms: "",
            meanings: "Tuyển dụng",
        },
        {
            id: 11,
            word: "Wait in line",
            synonyms: "Stand in line, line up",
            antonyms: "",
            meanings: "Xếp hàng",
        },
        {
            id: 12,
            word: "Current",
            synonyms: "Present",
            antonyms: "",
            meanings: "Hiện tại",
        },
        {
            id: 13,
            word: "Elevator",
            synonyms: "Lift",
            antonyms: "",
            meanings: "Thang máy",
        },
        {
            id: 14,
            word: "Escalator",
            synonyms: "",
            antonyms: "",
            meanings: "Thang cuốn",
        },
        {
            id: 15,
            word: "Out of service",
            synonyms: "Out of order",
            antonyms: "",
            meanings: "Ngưng phục vụ, hết, hư",
        },
        {
            id: 16,
            word: "Due to",
            synonyms: "Because of, owing to",
            antonyms: "",
            meanings: "Bởi vì",
        },
        {
            id: 17,
            word: "Display",
            synonyms: "Layout, exhibit",
            antonyms: "",
            meanings: "Trưng bày",
        },
        {
            id: 18,
            word: "Occupation",
            synonyms: "Profession, job, career",
            antonyms: "",
            meanings: "Nghề nghiệp",
        },
        {
            id: 19,
            word: "Decoration",
            synonyms: "Ornamentation",
            antonyms: "",
            meanings: "Sự trang trí",
        },
        {
            id: 20,
            word: "As of + ngày tháng",
            synonyms: "",
            antonyms: "",
            meanings: "Kể từ...trở đi",
        },
        {
            id: 21,
            word: "From now on",
            synonyms: "",
            antonyms: "",
            meanings: "Từ giờ trở đi",
        },
        {
            id: 22,
            word: "Refund",
            synonyms: "Money back (dùng khi mua hàng hóa)",
            antonyms: "",
            meanings: "Từ liên quan: policy, receipt, purchase,...",
        },
        {
            id: 23,
            word: "Reimburse(v) Reimbursement",
            synonyms: "Money back (dùng khi đi công tác)",
            antonyms: "",
            meanings: "Tiền thanh lại sau khi đi công tác. Từ liên quan: expense (chi phí), receipt, submit(nộp)...",
        },
        {
            id: 24,
            word: "Reduce",
            synonyms: "Cut, decrease, lessen",
            antonyms: "Rise, increase grow",
            meanings: "Giảm # Tăng. Từ liên quan: cost, price, budget, finanacial,...",
        },
        {
            id: 25,
            word: "Be in charge of",
            synonyms: "Take care of, take over",
            antonyms: "",
            meanings: "Đảm nhận",
        },
        {
            id: 26,
            word: "Postpone",
            synonyms: "Delay, put off, push back",
            antonyms: "",
            meanings: "Hoãn",
        },
        {
            id: 27,
            word: "Emergency",
            synonyms: "Urgent",
            antonyms: "",
            meanings: "Khẩn cấp",
        },
        {
            id: 28,
            word: "In advance",
            synonyms: "Before, prior to",
            antonyms: "",
            meanings: "Trước",
        },
        {
            id: 29,
            word: "Mandatory",
            synonyms: "Compulsory, must",
            antonyms: "Chú ý: Khi đề cho Requirement(s) thì tìm Require hoặc 1 trong 3 từ này",
            meanings: "Phải, bắt buộc",
        },
        {
            id: 30,
            word: "Inform",
            synonyms: "Announce, notify(v)",
            antonyms: "",
            meanings: "Thông báo",
        },
        {
            id: 31,
            word: "Get together",
            synonyms: "Meet together, gather",
            antonyms: "",
            meanings: "Gặp nhau",
        },
        {
            id: 32,
            word: "Focus on",
            synonyms: "Concentrate on",
            antonyms: "",
            meanings: "Tập trung vào",
        },
        {
            id: 33,
            word: "Cut",
            synonyms: "Trim, mow",
            antonyms: "",
            meanings: "Cắt, chặt, Cắt cỏ",
        },
        {
            id: 34,
            word: "Grass",
            synonyms: "Lawn",
            antonyms: "",
            meanings: "Cỏ",
        },
        {
            id: 35,
            word: "Income",
            synonyms: "Revenue, profit(n)",
            antonyms: "",
            meanings: "Lợi nhuận, thu nhập",
        },
        {
            id: 36,
            word: "Be out",
            synonyms: "Step out, go outside",
            antonyms: "",
            meanings: "Đi ra ngoài",
        },
        {
            id: 37,
            word: "Reduce rate",
            synonyms: "Discount, sale off, bargain, rebate",
            antonyms: "",
            meanings: "Giảm giá",
        },
        {
            id: 38,
            word: "50% discount",
            synonyms: "Half off, buy 1 get 1 free",
            antonyms: "",
            meanings: "Giảm 50%",
        },
        {
            id: 39,
            word: "Adjust",
            synonyms: "Test, check",
            antonyms: "",
            meanings: "Kiểm tra, điều chỉnh",
        },
        {
            id: 40,
            word: "Elect",
            synonyms: "Vote(v)",
            antonyms: "",
            meanings: "Bầu cử, bình chọn",
        },
        {
            id: 41,
            word: "Refreshments",
            synonyms: "Snacks and drinks",
            antonyms: "",
            meanings: "Thức ăn, nước uống(ăn nhẹ)",
        },
        {
            id: 42,
            word: "Enclosed",
            synonyms: "Included, sent (thư) Attached (email)",
            antonyms: "Chú ý: câu hỏi: gửi kèm cái gì thì tìm 1 trong những từ này",
            meanings: "Gửi kèm, đính kèm",
        },
        {
            id: 43,
            word: "Catering company",
            synonyms: "Food provider",
            antonyms: "",
            meanings: "Công ty phục vụ thức ăn nước uống",
        },
        {
            id: 44,
            word: "Bankrupt",
            synonyms: "Close the door, shut down",
            antonyms: "",
            meanings: "Phá sản",
        },
        {
            id: 45,
            word: "Register",
            synonyms: "Sign up, enroll",
            antonyms: "",
            meanings: "Đăng ký, ghi danh",
        },
        {
            id: 46,
            word: "Replacement",
            synonyms: "",
            antonyms: "",
            meanings: "Người or vật thay thế",
        },
        {
            id: 47,
            word: "Agreement",
            synonyms: "Contract, deal",
            antonyms: "",
            meanings: "Hợp đồng",
        },
        {
            id: 48,
            word: "Nationwide",
            synonyms: "Around the country, Throughout the country",
            antonyms: "",
            meanings: "Cả nước",
        },
        {
            id: 49,
            word: "Commence",
            synonyms: "Begin, start",
            antonyms: "",
            meanings: "Bắt đầu, khởi hành",
        },
        {
            id: 50,
            word: "Issue",
            synonyms: "Problem, matter",
            antonyms: "",
            meanings: "Vấn đề",
        },
        {
            id: 51,
            word: "Turn on",
            synonyms: "Switch on",
            antonyms: "Turn off, Switch off",
            meanings: "Mở, bật # tắt",
        },
        {
            id: 52,
            word: "Delighted",
            synonyms: "Happy",
            antonyms: "",
            meanings: "Vui, hạnh phúc",
        },
        {
            id: 53,
            word: "(1)Aim, (2)Goal",
            synonyms: "(1)Purpose, (2)Target <=> objective",
            antonyms: "",
            meanings: "(1)Mục đích, (2)Mục tiêu",
        },
        {
            id: 54,
            word: "Expected income",
            synonyms: "Desired pay",
            antonyms: "",
            meanings: "Thu nhập cao",
        },
        {
            id: 55,
            word: "Cover",
            synonyms: "Discuss",
            antonyms: "",
            meanings: "Bàn bạc, thảo luận",
        },
        {
            id: 56,
            word: "Retail shop",
            synonyms: "Bargain house",
            antonyms: "",
            meanings: "Cửa hàng bán lẻ",
        },
        {
            id: 57,
            word: "A quarter",
            synonyms: "Three months",
            antonyms: "",
            meanings: "1 quý",
        },
        {
            id: 58,
            word: "Popular",
            synonyms: "Common",
            antonyms: "",
            meanings: "Phổ biến",
        },
        {
            id: 59,
            word: "Work out",
            synonyms: "Exercise",
            antonyms: "",
            meanings: "Tập thể dục",
        },
        {
            id: 60,
            word: "The front page",
            synonyms: "The cover",
            antonyms: "",
            meanings: "Trang bìa",
        },
        {
            id: 61,
            word: "Freelance",
            synonyms: "Work independently",
            antonyms: "",
            meanings: "Làm nghề tự do",
        },
        {
            id: 62,
            word: "Stroll",
            synonyms: "Go for a work, walk, wander",
            antonyms: "",
            meanings: "Đi lang thang, đi dạo",
        },
        {
            id: 63,
            word: "Spare time",
            synonyms: "Free time",
            antonyms: "",
            meanings: "Thời gian rảnh",
        },
        {
            id: 64,
            word: "Day to day",
            synonyms: "Daily",
            antonyms: "",
            meanings: "Hàng ngày",
        },
        {
            id: 65,
            word: "Commemorate",
            synonyms: "Celebrate",
            antonyms: "",
            meanings: "Tưởng niệm, tổ chức",
        },
        {
            id: 66,
            word: "Worry about",
            synonyms: "Concern about",
            antonyms: "",
            meanings: "Lo lắng về",
        },
        {
            id: 67,
            word: "(1)Fair(adj) (2)Fair(n)",
            synonyms: "Equal",
            antonyms: "",
            meanings: "(1)Công bằng, bình đẳng. (2)Hội chợ",
        },
        {
            id: 68,
            word: "Reputation",
            synonyms: "",
            antonyms: "",
            meanings: "Danh tiếng",
        },
        {
            id: 69,
            word: "Affordable",
            synonyms: "Inexpensive, reasonable price",
            antonyms: "Expensive",
            meanings: "Giá hợp lý, không đắc",
        },
        {
            id: 70,
            word: "Reschedule",
            synonyms: "Change schedule",
            antonyms: "",
            meanings: "Đổi lịch",
        },
        {
            id: 71,
            word: "Purchase",
            synonyms: "Buy",
            antonyms: "",
            meanings: "Mua",
        },
        {
            id: 72,
            word: "Not change",
            synonyms: "Stay/remain the same, unchange",
            antonyms: "",
            meanings: "Không thay đổi",
        },
        {
            id: 73,
            word: "Firm",
            synonyms: "Factory, plant",
            antonyms: "",
            meanings: "Công ty, nhà máy",
        },
        {
            id: 74,
            word: "Candidate",
            synonyms: "Applicant",
            antonyms: "",
            meanings: "Người xin việc",
        },
        {
            id: 75,
            word: "Between...and...",
            synonyms: "Both...and.., From...to...",
            antonyms: "",
            meanings: "",
        },
        {
            id: 76,
            word: "Free of charge",
            synonyms: "No charge",
            antonyms: "",
            meanings: "Miễn phí",
        },
        {
            id: 77,
            word: "Quit",
            synonyms: "Stop",
            antonyms: "",
            meanings: "Quit the job = stop working",
        },
        {
            id: 78,
            word: "I'm in the mood",
            synonyms: "",
            antonyms: "",
            meanings: "Tôi đang thèm, muốn, đam mê,...",
        },
        {
            id: 79,
            word: "Participate in",
            synonyms: "Take part in, attend, join",
            antonyms: "",
            meanings: "Tham gia vào",
        },
        {
            id: 80,
            word: "Penatly",
            synonyms: "Fine(v)",
            antonyms: "",
            meanings: "Phạt",
        },
        {
            id: 81,
            word: "Repave",
            synonyms: "Resurface",
            antonyms: "",
            meanings: "Làm lại mặt đường",
        },
        {
            id: 82,
            word: "Opening",
            synonyms: "position",
            antonyms: "",
            meanings: "Vị trí tuyển dụng",
        },
        {
            id: 83,
            word: "Behind schedule (trễ tiến độ)",
            synonyms: "",
            antonyms: "Be on schedule, Meet the deadline",
            meanings: "Kịp tiến độ",
        },
        {
            id: 84,
            word: "Meet the requirement",
            synonyms: "Meet the need/ demand",
            antonyms: "",
            meanings: "Đáp ứng nhu cầu, yêu cầu",
        },
        {
            id: 85,
            word: "Hold(v)",
            synonyms: "",
            antonyms: "",
            meanings: "Cầm, giữ",
        },
        {
            id: 86,
            word: "Carry",
            synonyms: "",
            antonyms: "",
            meanings: "Xách, mang, bê...",
        },
        {
            id: 87,
            word: "Fold(v)",
            synonyms: "",
            antonyms: "",
            meanings: "Gấp, xếp",
        },
        {
            id: 88,
            word: "Take a bus/ train/...",
            synonyms: "Ride a bus/ train/",
            antonyms: "",
            meanings: "Đi bằng...",
        },
        {
            id: 89,
            word: "Do me a favor",
            synonyms: "Help me",
            antonyms: "",
            meanings: "Giúp tôi một việc",
        },
        {
            id: 90,
            word: "Take place",
            synonyms: "Hold -> held",
            antonyms: "",
            meanings: "Tổ chức, diễn ra",
        },
        {
            id: 91,
            word: "Present (v)",
            synonyms: "Make a presentation",
            antonyms: "",
            meanings: "Thuyết trình",
        },
        {
            id: 92,
            word: "Make an arrangement",
            synonyms: "Make an appointment",
            antonyms: "",
            meanings: "Hẹn",
        },
        {
            id: 93,
            word: "Make a reservation",
            synonyms: "Reserve, book",
            antonyms: "",
            meanings: "Đặt chỗ",
        },
        {
            id: 94,
            word: "Donate",
            synonyms: "Support",
            antonyms: "",
            meanings: "Tài trợ, hỗ trợ",
        },
        {
            id: 95,
            word: "Per",
            synonyms: "Each",
            antonyms: "Per/each/every + danh từ số ít",
            meanings: "Mỗi một",
        },
        {
            id: 96,
            word: "Be sure",
            synonyms: "Be certain",
            antonyms: "",
            meanings: "Hãy chắc chắn",
        },
        {
            id: 97,
            word: "Guarantee",
            synonyms: "Warranty",
            antonyms: "",
            meanings: "Đảm bảo, bảo hành",
        },
        {
            id: 98,
            word: "Valid",
            synonyms: "Liên quan: expire (hết hạn)",
            antonyms: "Invalid",
            meanings: "Có hiệu lực # hết hạn",
        },
        {
            id: 99,
            word: "Routine task",
            synonyms: "",
            antonyms: "",
            meanings: "Công việc thường ngày",
        },
        {
            id: 100,
            word: "Stack -->",
            synonyms: "Xếp chồng lên nhau",
            antonyms: "Pile -->",
            meanings: "Đổ đống",
        },
        {
            id: 101,
            word: "Located",
            synonyms: "Based",
            antonyms: "",
            meanings: "Nằm ở, tọa lạc",
        },
        {
            id: 102,
            word: "HR department",
            synonyms: "Personnel department",
            antonyms: "",
            meanings: "Phòng nhân sự",
        },
        {
            id: 103,
            word: "Biling statement",
            synonyms: "Receipt",
            antonyms: "",
            meanings: "Hóa đơn, biên nhận",
        },
        {
            id: 104,
            word: "Attorney",
            synonyms: "Lawyer",
            antonyms: "",
            meanings: "Luật sư, người được ủy nhiệm",
        },
        {
            id: 105,
            word: "Important",
            synonyms: "Vital, crucial",
            antonyms: "",
            meanings: "Quan trọng",
        },
        {
            id: 106,
            word: "Initially",
            synonyms: "First",
            antonyms: "",
            meanings: "Trước tiên, đầu tiên",
        },
        {
            id: 107,
            word: "Duty",
            synonyms: "Responsibility",
            antonyms: "",
            meanings: "Nhiệm vụ, trách nhiệm",
        },
        {
            id: 108,
            word: "Main office",
            synonyms: "Headquater",
            antonyms: "",
            meanings: "Trụ sở chính",
        },
        {
            id: 109,
            word: "Make-up",
            synonyms: "Cosmetic",
            antonyms: "",
            meanings: "Mỹ phẩm",
        },
]